media_entity_embeddable_video.settings:
  type: mapping
  label: 'Media entity embeddable video settings'
  mapping:
    local_images:
      type: string
      label: 'Base folder for tuhmbnails'
    grab_from:
      type: string
      label: 'From string used by Grab (sent with API requests)'
    aol_sid:
      type: string
      label: 'SID used by AOL (sent with API requests)'

media_entity.bundle.type.embeddable_video:
  type: mapping
  label: 'Embeddable video type configuration'
  mapping:
    source_field:
      type: string
      label: 'Field with embed code/URL'
